# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: adopt
        cache: maven
    - name: Build jar
      run: mvn --batch-mode --update-snapshots clean package -Dmaven.test.skip
    - name: Save jar
      uses: actions/upload-artifact@v2
      with:
        name: homeautomation-monitoring.jar
        path: target/homeautomation-monitoring.jar
    - name: Build Tests
      run: mvn --batch-mode test -DskipTests=true
    - name: Save target
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
          cache: maven
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
            name: target
            path: target
      - name: Test
        run: mvn --batch-mode test
  integration-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
          cache: maven
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
            name: target
            path: target
      - name: Test
        run: mvn --batch-mode failsafe:integration-test -Dskip.surefire.tests
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - name: Restore artifact
        uses: actions/download-artifact@v2
        with:
            name: homeautomation-monitoring.jar
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: homeautomation-monitoring.jar
            asset_name: homeautomation-monitoring.jar
            tag: ${{ github.ref }}-snapshot
            overwrite: true
